name = "lean-playground"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["leanplayground"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanPlayground"

[[lean_exe]]
name = "leanplayground"
root = "Main"